Merge continuous_anomal_values
UBESP-DCTV/csm pull request #11
Opened 2020-02-13 09:33 UTC by danielebottigliengo

Merge the feature `continuous_anomal_values` to the develop branch. In the branch the body and the tests related to the function `categorical_anomal_values` are presente (my mistake).

2020-02-14 11:29 UTC, CorradoLanera commented
Vedi, quello che dicevo: quando apri un ramo di sviluppo, devi sempre essere sicuro che comunque resti costantemente aggiornato con integrate le ultime modifiche incorporate nel ramo develop.

2020-02-14 16:00 UTC, CorradoLanera requested changes
Mi pare benone, alcune piccole modifiche sia alle funzioni che ai test (in particolare la restituzione degli NA non mi garba molto). Per il resto sono tante ma di fatto sono le stesse 3-4 cose ripetute nei vari punti in cui appaiono

2020-02-14 16:00 UTC, CorradoLanera commented on R/continuous_anomal_values.R
Meglio definire gli oggetti esternamente, credo sia più chiaro e permette di gestire meglio potenziali errori (risolvibili in modo automatico, se vogliamo)

```
    min <- range[[1]]
    max <- range[[2]]
    
    if (max < min) {
        warning("Max in range is below the min. They will be switched.")
        aux <- max
        max <- min
        min <- aux
    }


  out_of_range <- x < min | x > max
```

2020-02-14 16:00 UTC, CorradoLanera commented on R/continuous_anomal_values.R
> +    if (length(extreme) == 0) {NA_real_} else {extreme}
Se non ci sono elementi oltre gli estremi, l'insieme di tali elemeniti è un reale..vuoto. Perche vuoi restituire un NA? Non siamo in caso di dubbio, sappiamo perfettamente che non ce ne sono...

metterei


```
x[out_of_range]
```

e basta.

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    range   <- c(6, 9)
La definizione degli oggetti che usi la sposterei fuori dai test in modo da farli computare una sola volta

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    range   <- c(2, 20)
Spostando fuori, questo non serve più

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    range   <- "aa"
Spostando fuori questo non serve più

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    range   <- c(5, 8)
Spostando fuori questo non serve più

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    range <- c(5, 8)
Spostando fuori questo non serve più

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    x <- rnorm(n = 10L, mean = 10, sd = 2)
Spostando fuori questo non serve più

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    expect_error(continuous_anomal_values(x = x))
inserire il testo, o parte, dell'errore, se no potrebbe passare perchè da errore ma per un motivo diverso da quello che pensi tu

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    expect_error(continuous_anomal_values(range = range))
inserire il testo, o parte, dell'errore, se no potrebbe passare perchè da errore ma per un motivo diverso da quello che pensi tu

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    expect_error(continuous_anomal_values(x = x, range = range))
inserire il testo, o parte, dell'errore, se no potrebbe passare perchè da errore ma per un motivo diverso da quello che pensi tu

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +    expect_error(continuous_anomal_values(x = x, range = range))
inserire il testo, o parte, dell'errore, se no potrebbe passare perchè da errore ma per un motivo diverso da quello che pensi tu

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +test_that("Error when a string is passed to x", {
Se non si è mai verificato, non serve testarlo. Prima regola: non implementare cose che pensi forse un domani potrebbero servire in futuro. Se mai questo errore accadrà, lo controllerai, scriverai un test, e farai in modo che poi la tua funzione ne sia protetto.

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-continuous_anomal_values.R
> +test_that("NA if all the values are inside the range", {
Su questo non sono daccordo, se sono tutti dentro, i valori fuori non sono ignoti, non ce ne sono: dovrebbe essere un `numeric(0)`, cjhe è esattamente qeullo che restisce la funzione, come scritta, in modo naturale. Piuttosto controlla che abbia lunghezza zero! ;-)

2020-02-14 16:00 UTC, CorradoLanera commented on R/categorical_anomal_values.R
> +    assertive::assert_is_character(x)
e se è un fattore?

2020-02-14 16:00 UTC, CorradoLanera commented on R/categorical_anomal_values.R
> +    if (all(out_values)) {NA_character_} else {x[!out_values]}
Come per il continuo, se non ci sono valori anomali, l'insieme dei valori anomali c'è, esiste, è di classe character...ed è vuoto di lunghezza zero! 

lascierei semplicemente (riscrivendo i nomi delle variabili in modo che siano coerenti con il contenuto...)

```
out_values <- !(x %in% values)
x[out_values]
```

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +    values <- c("male", "female")
Sposterei fuori la creazione degli oggetti così li crei una volta sola

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +    values <- c("male", "female")
Sposterei fuori la creazione degli oggetti così li crei una volta sola

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +    )
Non sono d''ccordo, dovrebbe essere un vettore di caratteri di lunghezza zero, non un qualcosa di ignoto

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +test_that("Error when a numerico is passed to x", {
Testa solo erorri che sono effettivamente accaduti...

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +test_that("Error when a string is passed to values", {
Testa solo errori che sono effettivamente accaduti

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +    expect_error(continuous_anomal_values(x = x, range = range))
Aggiungi il testo dell'errore quando fai questi controlli, o rischi che passino perchè da errore per un motivo diverso da quello che credi

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +    expect_error(continuous_anomal_values(range = range))
Aggiungi il testo dell'errore quando fai questi controlli, o rischi che passino perchè da errore per un motivo diverso da quello che credi

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +    expect_error(continuous_anomal_values(x = x))
Aggiungi il testo dell'errore quando fai questi controlli, o rischi che passino perchè da errore per un motivo diverso da quello che credi

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +    x <- c("male", "female", "male", "male", "female")
Sposterei fuori la creazione degli oggetti così li crei una volta sola

2020-02-14 16:00 UTC, CorradoLanera commented on tests/testthat/test-categorical_anomal_values.R
> +    values <- c("male", "female")
Sposterei fuori la creazione degli oggetti così li crei una volta sola

2020-02-17 10:05 UTC, danielebottigliengo commented on R/continuous_anomal_values.R
Ok, sistemato.

2020-02-17 10:13 UTC, danielebottigliengo commented on R/continuous_anomal_values.R
> +    if (length(extreme) == 0) {NA_real_} else {extreme}
Ok. Avevo messo di restituire NA perchè avevo pensato fosse più facile da gestire successivamente in seguito rispetto a un output tipo `numeric(0)`. Risolto.

2020-02-17 10:18 UTC, danielebottigliengo commented on tests/testthat/test-continuous_anomal_values.R
> +    range   <- c(6, 9)
Risolto

2020-02-17 11:49 UTC, danielebottigliengo commented on tests/testthat/test-continuous_anomal_values.R
> +    range   <- c(2, 20)
Risolto.

2020-02-17 11:49 UTC, danielebottigliengo commented on tests/testthat/test-continuous_anomal_values.R
> +    range   <- "aa"
Risolto.

2020-02-17 12:00 UTC, danielebottigliengo commented on tests/testthat/test-categorical_anomal_values.R
> +    expect_error(continuous_anomal_values(x = x, range = range))
Risolto.

2020-02-17 12:10 UTC, CorradoLanera approved these changes

2020-02-17 13:10 UTC, CorradoLanera commented
risposto in #14

2020-02-17 14:09 UTC, merged